services:
  api:
    build: .
    container_name: middleware_api_C216
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always
  
  tests:
    build: .
    container_name: middleware_tests_C216
    volumes:
      - .:/app
    command: pytest -v